# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa76a10590371f1eca4be9aa97419f3cdc3d8fd1b259698e1977281df22d0124a686d81d1e33c51acefe0a18760524ae8f7030cacb59bd2a3cbac491814c3608

test:
  secret_key_base: e129974c636fcb960c09797a5cc8e31acb855c90b15d08265205cb26516a87590590ac53e8b47b980a8e0772f0487609ff704cab99c6bdbfb16b0884059e0f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
